import { Metrophobic, Manrope } from "next/font/google";
import "./globals.css";
import Nav from "@/components/shared/Nav";
import Footer from "@/components/shared/Footer";

const metrophobic = Metrophobic({ subsets: ["latin"], weight: '400', variable: '--font-metrophobic' });
const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.className} ${metrophobic.variable}`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
